version: '3.7'
services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - docker-vol:/var/lib/docker

  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: tcp://dind:2375
    depends_on:
      - dind

volumes:
  jenkins-data:
  docker-vol: